# -*- coding: utf-8 -*-
"""appBencana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xvBbrq_ottjspV80OzvTTS2IpTQ6o2yQ
"""

import streamlit as st
import pandas as pd
import altair as alt

# Konfigurasi Halaman
st.set_page_config(page_title="Dashboard Kehutanan & Bencana Indonesia", layout="wide")

# Fungsi untuk membersihkan angka format Indonesia (titik ribuan, koma desimal)
def clean_id_number(series):
    return pd.to_numeric(series.astype(str).str.replace('.', '', regex=False).str.replace(',', '.'), errors='coerce')

# 1. Load Data
@st.cache_data
def load_data():
    # Tree Cover Loss
    df_loss = pd.read_excel('treecoverloss2001-2024.xlsx')

    # Deforestasi (Cleaning numeric columns)
    df_def = pd.read_excel('deforestasi2024.xlsx')
    for col in ['HK', 'HL', 'HPT', 'HP', 'HPK', 'APL']:
        df_def[col] = clean_id_number(df_def[col])

    # Kasus Kehutanan
    df_kasus = pd.read_excel('kasushutan_2024.xlsx')
    df_kasus.columns = df_kasus.columns.str.strip()
    df_kasus['JUMLAH'] = clean_id_number(df_kasus['JUMLAH'])
    # Ensure all numeric columns are properly typed
    for col in df_kasus.columns:
        if col != 'PROVINSI' and col not in ['ILLEGAL_LOGGING', 'PERAMBAHAN_HUTAN', 'TUMBUHAN_SATWA_LIAR']:
            df_kasus[col] = pd.to_numeric(df_kasus[col], errors='coerce')

    # Data Bencana
    df_bencana = pd.read_excel('Dataset_Bencana_Nasional_Lengkap.xlsx')

    return df_loss, df_def, df_kasus, df_bencana

df_loss, df_def, df_kasus, df_bencana = load_data()

# --- HEADER ---
st.title("🌲 Analisis Kondisi Hutan dan Dampak Lingkungan")
st.markdown("""
Dashboard ini menyajikan narasi visual mengenai kondisi tutupan hutan di Indonesia,
pelanggaran hukum yang terjadi, hingga kaitannya dengan bencana alam yang terekam.
""")

# --- BAGIAN 1: TREN KEHILANGAN TUTUPAN POHON ---
st.header("1. Tren Kehilangan Tutupan Pohon (2001-2024)")
col1, col2 = st.columns([3, 1])

with col1:
    line_chart = alt.Chart(df_loss).mark_line(point=True, color='#e63946').encode(
        x=alt.X('year:O', title='Tahun'),
        y=alt.Y('loss_ha:Q', title='Luas Kehilangan (Ha)'),
        tooltip=['year', 'loss_ha']
    ).interactive()
    st.altair_chart(line_chart, use_container_width=True)

with col2:
    st.write("**Narasi:**")
    total_loss = df_loss['loss_ha'].sum()
    st.info(f"Total kehilangan tutupan pohon sejak 2001 mencapai **{total_loss:,.0f} Ha**.")
    st.write("Fluktuasi angka tahunan menunjukkan dinamika perubahan penggunaan lahan dan efektivitas kebijakan proteksi hutan.")

# --- BAGIAN 2: STATUS HUTAN PER PROVINSI ---
st.header("2. Sebaran Luas Hutan Berdasarkan Fungsi")
provinsi_select = st.selectbox("Pilih Provinsi:", df_def['PROVINSI'].unique())

df_def_filtered = df_def[df_def['PROVINSI'] == provinsi_select].melt(
    id_vars='PROVINSI', value_vars=['HK', 'HL', 'HPT', 'HP', 'HPK', 'APL'],
    var_name='Fungsi Hutan', value_name='Luas (Ha)'
)

bar_chart = alt.Chart(df_def_filtered).mark_bar().encode(
    x=alt.X('Fungsi Hutan', sort='-y'),
    y='Luas (Ha)',
    color=alt.Color('Fungsi Hutan', scale=alt.Scale(scheme='viridis')),
    tooltip=['Fungsi Hutan', 'Luas (Ha)']
)
st.altair_chart(bar_chart, use_container_width=True)

st.caption("HK: Hutan Konservasi, HL: Hutan Lindung, HP: Hutan Produksi, APL: Area Penggunaan Lain.")

# --- BAGIAN 3: KRIMINALITAS KEHUTANAN ---
st.header("3. Pelanggaran Hukum Kehutanan 2024")
top_kasus = df_kasus.sort_values('JUMLAH', ascending=False).head(10)

kasus_chart = alt.Chart(top_kasus).mark_bar(color='#457b9d').encode(
    x=alt.X('JUMLAH:Q', title='Jumlah Kasus'),
    y=alt.Y('PROVINSI:N', sort='-x', title='Provinsi'),
    tooltip=[alt.Tooltip('PROVINSI:N'),
             alt.Tooltip('JUMLAH:Q', format=','),
             alt.Tooltip('ILLEGAL_LOGGING:N', format=''),
             alt.Tooltip('PERAMBAHAN_HUTAN:N', format=''),
             alt.Tooltip('TUMBUHAN_SATWA_LIAR:N', format='')]
)
st.altair_chart(kasus_chart, use_container_width=True)
st.write("> **Catatan:** Grafik di atas menunjukkan 10 provinsi dengan jumlah kasus tertinggi. Hover (arahkan kursor) pada batang grafik untuk melihat detail jenis pelanggaran.")

# --- BAGIAN 4: HUBUNGAN DENGAN BENCANA ---
st.header("4. Rekapitulasi Kejadian Bencana 2025")
bencana_count = df_bencana['Total Bencana'].value_counts().reset_index(name='Jumlah Kejadian')
bencana_count.columns = ['Jenis Bencana', 'Jumlah Kejadian']

col_a, col_b = st.columns(2)

with col_a:
    pie_bencana = alt.Chart(bencana_count).mark_arc().encode(
        theta=alt.Theta(field="Jumlah Kejadian", type="quantitative"),
        color=alt.Color(field="Jenis Bencana", type="nominal"),
        tooltip=['Jenis Bencana', 'Jumlah Kejadian']
    )
    st.altair_chart(pie_bencana, use_container_width=True)

with col_b:
    st.write("**Dampak Bencana Terkini:**")
    total_rusak = df_bencana['Total Rumah Rusak'].sum()
    total_mengungsi = df_bencana['Mengungsi'].sum()
    total_meninggal = df_bencana['Meninggal'].sum()
    st.metric("Total Rumah Rusak", f"{total_rusak:,.0f}")
    st.metric("Total Orang Mengungsi", f"{total_mengungsi:,.0f}")
    st.metric("Korban Jiwa", f"{total_meninggal:,.0f}")

st.markdown("---")
# --- BAGIAN 5: TAHUN DENGAN KEHILANGAN TUTUPAN HUTAN TERBANYAK ---
st.header("5. Peringkat Tahun Berdasarkan Kehilangan Tutupan Hutan")
df_loss_top_years = df_loss.sort_values('loss_ha', ascending=False).head(10)

loss_year_chart = alt.Chart(df_loss_top_years).mark_bar(color='#d90429').encode(
    x=alt.X('loss_ha:Q', title='Total Kehilangan (Ha)'),
    y=alt.Y('year:O', sort='-x', title='Tahun'),
    tooltip=['year', 'loss_ha']
)
st.altair_chart(loss_year_chart, use_container_width=True)
st.write("> **Catatan:** Grafik ini menampilkan 10 tahun dengan kehilangan tutupan hutan tertinggi dari tahun 2001-2024.")

# --- BAGIAN 6: DAMPAK BENCANA PER PROVINSI ---
st.header("6. Rincian Dampak Bencana per Provinsi")
provinsi_bencana_select = st.selectbox("Pilih Provinsi untuk Melihat Dampak Bencana:", df_bencana['Provinsi'].unique())

df_bencana_prov = df_bencana[df_bencana['Provinsi'] == provinsi_bencana_select]
dampak_data = df_bencana_prov[['Meninggal', 'Mengungsi', 'Total Rumah Rusak']].sum().reset_index()
dampak_data.columns = ['Jenis Dampak', 'Jumlah']

dampak_chart = alt.Chart(dampak_data).mark_bar(color='#fca311').encode(
    x=alt.X('Jumlah:Q', title='Jumlah'),
    y=alt.Y('Jenis Dampak:N', sort='-x', title='Dampak'),
    tooltip=['Jenis Dampak', 'Jumlah']
)
st.altair_chart(dampak_chart, use_container_width=True)
st.write("> **Catatan:** Grafik ini merinci jumlah korban jiwa, pengungsi, dan rumah rusak akibat bencana di provinsi yang dipilih.")

# --- BAGIAN 7: JENIS PELANGGARAN KEHUTANAN ---
st.header("7. Komposisi Jenis Pelanggaran di Provinsi Teratas")
top_10_provinsi_kasus = df_kasus.sort_values('JUMLAH', ascending=False).head(10)
kasus_melted = top_10_provinsi_kasus.melt(
    id_vars='PROVINSI',
    value_vars=['ILLEGAL_LOGGING', 'PERAMBAHAN_HUTAN', 'TUMBUHAN_SATWA_LIAR'],
    var_name='Jenis Pelanggaran',
    value_name='Jumlah Kasus'
)

stacked_bar_kasus = alt.Chart(kasus_melted).mark_bar().encode(
    x=alt.X('sum(Jumlah Kasus):Q', title='Total Kasus'),
    y=alt.Y('PROVINSI:N', sort=alt.EncodingSortField(field="sum(Jumlah Kasus)", op="sum", order='descending')),
    color=alt.Color('Jenis Pelanggaran:N', scale=alt.Scale(scheme='category10')),
    tooltip=['PROVINSI', 'Jenis Pelanggaran', 'Jumlah Kasus']
)
st.altair_chart(stacked_bar_kasus, use_container_width=True)
st.write("> **Catatan:** Grafik ini menunjukkan komposisi tiga jenis pelanggaran utama di 10 provinsi dengan jumlah kasus kehutanan tertinggi.")

# --- BAGIAN 8: JENIS BENCANA PER PROVINSI ---
st.header("8. Sebaran Jenis Bencana per Provinsi")
prov_bencana_select = st.selectbox("Pilih Provinsi untuk Melihat Sebaran Bencana:", df_bencana['Provinsi'].unique(), key='prov_bencana_selectbox')

df_bencana_prov_jenis = df_bencana[df_bencana['Provinsi'] == prov_bencana_select]
bencana_jenis_count = df_bencana_prov_jenis['Total Bencana'].value_counts().reset_index()
bencana_jenis_count.columns = ['Jenis Bencana', 'Jumlah Kejadian']

jenis_bencana_chart = alt.Chart(bencana_jenis_count).mark_bar(color='#1d3557').encode(
    x=alt.X('Jumlah Kejadian:Q', title='Jumlah Kejadian'),
    y=alt.Y('Jenis Bencana:N', sort='-x', title='Jenis Bencana'),
    tooltip=['Jenis Bencana', 'Jumlah Kejadian']
)
st.altair_chart(jenis_bencana_chart, use_container_width=True)
st.write("> **Catatan:** Grafik ini menampilkan frekuensi berbagai jenis bencana yang terjadi di provinsi yang dipilih.")

# --- BAGIAN 9: KORELASI BENCANA DAN KERUSAKAN ---
st.header("9. Hubungan Antara Jumlah Kejadian Bencana dan Rumah Rusak")
df_bencana_agg = df_bencana.groupby('Provinsi').agg(
    Total_Kejadian=('Total Bencana', 'count'),
    Total_Rumah_Rusak=('Total Rumah Rusak', 'sum')
).reset_index()

scatter_bencana = alt.Chart(df_bencana_agg).mark_circle(size=100).encode(
    x=alt.X('Total_Kejadian:Q', title='Jumlah Kejadian Bencana'),
    y=alt.Y('Total_Rumah_Rusak:Q', title='Total Rumah Rusak'),
    tooltip=['Provinsi', 'Total_Kejadian', 'Total_Rumah_Rusak'],
    color=alt.value('#e63946')
).interactive()

st.altair_chart(scatter_bencana, use_container_width=True)
st.write("> **Catatan:** Scatter plot ini menunjukkan hubungan antara total kejadian bencana dan jumlah rumah rusak di setiap provinsi. Arahkan kursor ke titik untuk melihat detail provinsi.")

# --- BAGIAN 10: PERBANDINGAN FUNGSI HUTAN DAN KEHILANGAN TUTUPAN ---
st.header("10. Luas Fungsi Hutan vs. Total Kehilangan Tutupan Hutan")
prov_compare_select = st.selectbox("Pilih Provinsi untuk Perbandingan:", df_def['PROVINSI'].unique(), key='prov_compare_selectbox')

# Data Fungsi Hutan
df_def_prov = df_def[df_def['PROVINSI'] == prov_compare_select].melt(
    id_vars='PROVINSI', value_vars=['HK', 'HL', 'HPT', 'HP', 'HPK', 'APL'],
    var_name='Kategori', value_name='Luas (Ha)'
)

# Data Kehilangan Tutupan Hutan
# Since df_loss does not have province data, we'll show the total loss for context.
# A better approach would be to have province data in the loss dataset.
total_loss_all_provinces = df_loss['loss_ha'].sum()
loss_df = pd.DataFrame([{'PROVINSI': prov_compare_select, 'Kategori': 'Total Kehilangan (Nasional)', 'Luas (Ha)': total_loss_all_provinces}])

# Gabungkan data
combined_df = pd.concat([df_def_prov, loss_df])

comparison_chart = alt.Chart(combined_df).mark_bar().encode(
    x=alt.X('Kategori:N', sort='-y', title='Kategori'),
    y=alt.Y('Luas (Ha):Q', title='Luas (Ha)'),
    color=alt.Color('Kategori:N', legend=None, scale=alt.Scale(scheme='spectral')),
    tooltip=['Kategori', 'Luas (Ha)']
)

st.altair_chart(comparison_chart, use_container_width=True)
st.write("> **Catatan:** Grafik ini membandingkan luas area berdasarkan fungsi hutan dengan total akumulasi kehilangan tutupan hutan di provinsi terpilih. Ini membantu melihat skala kehilangan hutan relatif terhadap luas hutan yang ada.")

st.markdown("Analisis ini menunjukkan bahwa wilayah dengan tingkat deforestasi tinggi atau aktivitas ilegal seringkali memiliki kerentanan terhadap bencana hidrometeorologi seperti banjir dan cuaca ekstrem.")
